import markdown2
import os
import sys
from pathlib import Path
from datetime import datetime

# ============================================
# Markdown to PDF Converter
# Day 57 — 120 Days of Code | NIT Rourkela
# ============================================

THEMES = {
    "light": {
        "bg": "#ffffff", "text": "#1a1a1a", "heading": "#7c3aed",
        "code_bg": "#f3f3f7", "border": "#e0e0e0"
    },
    "dark": {
        "bg": "#0a0a0a", "text": "#f0f0f0", "heading": "#c084fc",
        "code_bg": "#1a1a2e", "border": "#2a2a4a"
    },
    "academic": {
        "bg": "#fdfdfb", "text": "#2c2c2c", "heading": "#1a365d",
        "code_bg": "#f5f5f0", "border": "#cccccc"
    }
}

def build_css(theme_name="light"):
    t = THEMES.get(theme_name, THEMES["light"])
    return f"""
    @page {{ margin: 2cm; }}
    body {{
        font-family: 'Helvetica Neue', Arial, sans-serif;
        background: {t['bg']};
        color: {t['text']};
        line-height: 1.7;
        font-size: 11pt;
    }}
    h1, h2, h3 {{ color: {t['heading']}; margin-top: 1.2em; }}
    h1 {{ font-size: 24pt; border-bottom: 2px solid {t['heading']}; padding-bottom: 8px; }}
    h2 {{ font-size: 18pt; }}
    h3 {{ font-size: 14pt; }}
    p {{ margin: 0.8em 0; }}
    code {{
        background: {t['code_bg']};
        padding: 2px 6px;
        border-radius: 4px;
        font-family: 'Courier New', monospace;
        font-size: 0.9em;
    }}
    pre {{
        background: {t['code_bg']};
        padding: 14px;
        border-radius: 8px;
        overflow-x: auto;
        border-left: 3px solid {t['heading']};
    }}
    pre code {{ background: none; padding: 0; }}
    blockquote {{
        border-left: 3px solid {t['heading']};
        padding-left: 16px;
        color: #666;
        font-style: italic;
        margin: 1em 0;
    }}
    table {{ border-collapse: collapse; width: 100%; margin: 1em 0; }}
    th, td {{ border: 1px solid {t['border']}; padding: 8px 12px; text-align: left; }}
    th {{ background: {t['code_bg']}; }}
    a {{ color: {t['heading']}; }}
    ul, ol {{ padding-left: 24px; }}
    li {{ margin: 4px 0; }}
    .footer {{
        margin-top: 3em;
        padding-top: 1em;
        border-top: 1px solid {t['border']};
        font-size: 9pt;
        color: #888;
        text-align: center;
    }}
    """

def convert_file(md_path, output_path=None, theme="light"):
    md_file = Path(md_path)
    if not md_file.exists():
        print(f"❌ File not found: {md_path}")
        return False

    with open(md_file, 'r', encoding='utf-8') as f:
        md_text = f.read()

    html_body = markdown2.markdown(
        md_text,
        extras=['fenced-code-blocks', 'tables', 'header-ids', 'toc']
    )

    css = build_css(theme)
    timestamp = datetime.now().strftime('%Y-%m-%d %H:%M')

    full_html = f"""
    <!DOCTYPE html>
    <html>
    <head><meta charset="utf-8"><style>{css}</style></head>
    <body>
        {html_body}
        <div class="footer">
            Generated by Markdown to PDF Converter · {timestamp}
        </div>
    </body>
    </html>
    """

    if output_path is None:
        output_path = md_file.with_suffix('.pdf')

    try:
        from weasyprint import HTML
        HTML(string=full_html).write_pdf(str(output_path))
        print(f"✅ PDF created with WeasyPrint: {output_path}")
        return True
    except ImportError:
        pass

    try:
        import pdfkit
        pdfkit.from_string(full_html, str(output_path))
        print(f"✅ PDF created with pdfkit: {output_path}")
        return True
    except ImportError:
        pass

    # Fallback: just save the styled HTML
    html_output = md_file.with_suffix('.html')
    with open(html_output, 'w', encoding='utf-8') as f:
        f.write(full_html)
    print(f"⚠️  No PDF library available — saved styled HTML instead: {html_output}")
    print("   Open it in a browser and use Print → Save as PDF")
    return False

def batch_convert(folder, theme="light"):
    folder_path = Path(folder)
    if not folder_path.exists():
        print(f"❌ Folder not found: {folder}")
        return

    md_files = list(folder_path.glob("*.md"))
    if not md_files:
        print(f"No .md files found in {folder}")
        return

    print(f"\nFound {len(md_files)} markdown file(s)\n")
    success = 0
    for md_file in md_files:
        print(f"Converting: {md_file.name}...")
        if convert_file(md_file, theme=theme):
            success += 1

    print(f"\n✅ {success}/{len(md_files)} files converted successfully")

def create_sample():
    sample = """# Sample Document

## Introduction

This is a **sample markdown** document to test the converter.

## Features

- Bullet points work
- *Italic* and **bold** text
- `inline code` formatting

## Code Example

```python
def hello():
    print("Hello from Day 57!")
```

## Table

| Day | Project |
|-----|---------|
| 1   | Hello World |
| 57  | MD to PDF Converter |

> This is a blockquote demonstrating styled formatting.

## Conclusion

This document was generated to test the **Markdown to PDF Converter**
built on Day 57 of the 120 Days of Code challenge.
"""
    with open("sample.md", "w") as f:
        f.write(sample)
    print("✅ Created sample.md")
    return "sample.md"

def main():
    print("=" * 55)
    print("  Markdown to PDF Converter — Day 57 of 120")
    print("=" * 55)
    print("\n  1. Convert a single file")
    print("  2. Batch convert a folder")
    print("  3. Try with sample document")

    choice = input("\n  Choose (1/2/3): ").strip()

    theme = input("  Theme (light/dark/academic) [light]: ").strip() or "light"

    if choice == "1":
        path = input("  Enter .md file path: ").strip()
        convert_file(path, theme=theme)
    elif choice == "2":
        folder = input("  Enter folder path: ").strip()
        batch_convert(folder, theme=theme)
    elif choice == "3":
        sample_path = create_sample()
        convert_file(sample_path, theme=theme)
    else:
        print("  ❌ Invalid choice!")

main()